name: "Backend"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node modules
        run: |
          cd backend
          yarn install
      - name: Build project
        run: |
          cd backend
          yarn build
      - name: Start project
        run: |
          cd backend
          cp .env.example .env
          yarn start
      - name: Unit & Integration tests
        run: |
          cd backend
          yarn test
