name: "Frontend"

on: 
   workflow_call:
     inputs:
       environment:
         required: true
         type: string

jobs:
   install-frontend:
     runs-on: ubuntu-latest
     defaults:
        run: 
           working-directory: frontend
     steps:
       - name: Install Node modules
         run: yarn ci
