name: "Frontend"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest

    steps:
      - name: Install Node modules
        run: yarn install
      - name: Typecheck
        run: yarn typecheck
      - name: Linting
        run: yarn lint
      - name: Unit & Integration tests
        run: yarn test
      - name: Build
        run: yarn build:web
