name: "Frontend"

on:
  push:
    paths:
      - "frontend/**"

jobs:
  test-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node modules
        run: yarn install --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
      - name: Linting
        run: yarn lint
      - name: Unit & Integration tests
        run: yarn test
      - name: Build
        run: yarn build:web
