name: github-pipeline
run-name: ${{ github.actor }}, ${{ github.ref_name }}🚀

on: [push]

jobs:
  #Frontend job
  frontend:
    needs: workflow-setup
    uses: ./.github/workflows/frontend.yml
    with:
      environment: develop

  #Backend job
  backend:
    needs: workflow-setup
    uses: ./.github/workflows/backend.yml
    with:
      environment: develop
