name: github-pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  #First job
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - name: Install Node modules
        run: yarn ci
