name: github-pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  #Frontend
  frontend:
    uses: ./.github/workflows/frontend.yml
    with:
      environment: develop
